application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      kukla-integration-service:
        license: Apache-2.0
        actions:
          get-products:
            function: actions/get-products/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL_STAGING: $RUNTIME_URL_STAGING
              RUNTIME_URL_PRODUCTION: $RUNTIME_URL_PRODUCTION
              RUNTIME_NAMESPACE: $RUNTIME_NAMESPACE
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
              COMMERCE_CONSUMER_KEY:
                type: string
                description: OAuth 1.0 consumer key for Commerce API authentication
              COMMERCE_CONSUMER_SECRET:
                type: string
                description: OAuth 1.0 consumer secret for Commerce API authentication
              COMMERCE_ACCESS_TOKEN:
                type: string
                description: OAuth 1.0 access token for Commerce API authentication
              COMMERCE_ACCESS_TOKEN_SECRET:
                type: string
                description: OAuth 1.0 access token secret for Commerce API authentication
            annotations:
              require-adobe-auth: false
              final: true
          download-file:
            function: actions/download-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL_STAGING: $RUNTIME_URL_STAGING
              RUNTIME_URL_PRODUCTION: $RUNTIME_URL_PRODUCTION
              RUNTIME_NAMESPACE: $RUNTIME_NAMESPACE
            annotations:
              require-adobe-auth: false
              final: true
          browse-files:
            function: actions/browse-files/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL_STAGING: $RUNTIME_URL_STAGING
              RUNTIME_URL_PRODUCTION: $RUNTIME_URL_PRODUCTION
              RUNTIME_NAMESPACE: $RUNTIME_NAMESPACE
            annotations:
              require-adobe-auth: false
              final: true
          delete-file:
            function: actions/delete-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL_STAGING: $RUNTIME_URL_STAGING
              RUNTIME_URL_PRODUCTION: $RUNTIME_URL_PRODUCTION
              RUNTIME_NAMESPACE: $RUNTIME_NAMESPACE
            annotations:
              require-adobe-auth: false
              final: true
          get-products-mesh:
            function: actions/get-products-mesh/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              MESH_API_KEY: $MESH_API_KEY
              API_MESH_ENDPOINT: $API_MESH_ENDPOINT
              RUNTIME_URL_STAGING: $RUNTIME_URL_STAGING
              RUNTIME_URL_PRODUCTION: $RUNTIME_URL_PRODUCTION
              RUNTIME_NAMESPACE: $RUNTIME_NAMESPACE
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
              COMMERCE_CONSUMER_KEY:
                type: string
                description: OAuth 1.0 consumer key for Commerce API authentication
              COMMERCE_CONSUMER_SECRET:
                type: string
                description: OAuth 1.0 consumer secret for Commerce API authentication
              COMMERCE_ACCESS_TOKEN:
                type: string
                description: OAuth 1.0 access token for Commerce API authentication
              COMMERCE_ACCESS_TOKEN_SECRET:
                type: string
                description: OAuth 1.0 access token secret for Commerce API authentication
              MESH_API_KEY:
                type: string
                description: API key for API Mesh authentication
            annotations:
              require-adobe-auth: false
              final: true
