application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      kukla-integration-service:
        license: Apache-2.0
        actions:
          get-products:
            function: actions/get-products/index.js
            web: "yes"
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              MAGENTO_ADMIN_USERNAME: $MAGENTO_ADMIN_USERNAME
              MAGENTO_ADMIN_PASSWORD: $MAGENTO_ADMIN_PASSWORD
              MAGENTO_API_BASE_URL: $MAGENTO_API_BASE_URL
              MAGENTO_CONSUMER_KEY: $MAGENTO_CONSUMER_KEY
              MAGENTO_CONSUMER_SECRET: $MAGENTO_CONSUMER_SECRET
              MAGENTO_ACCESS_TOKEN: $MAGENTO_ACCESS_TOKEN
              MAGENTO_ACCESS_TOKEN_SECRET: $MAGENTO_ACCESS_TOKEN_SECRET
            annotations:
              require-adobe-auth: false
              final: true
