application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      kukla-integration-service:
        license: Apache-2.0
        actions:
          get-products:
            function: actions/backend/get-products/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
            annotations:
              require-adobe-auth: false
              final: true
          download-file:
            function: actions/backend/download-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            annotations:
              require-adobe-auth: false
              final: true
          browse-files:
            function: actions/frontend/browse-files/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            annotations:
              require-adobe-auth: false
              final: true
          delete-file:
            function: actions/backend/delete-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            annotations:
              require-adobe-auth: false
              final: true
          get-products-mesh:
            function: actions/backend/get-products-mesh/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              MESH_API_KEY: $MESH_API_KEY
              CATALOG_SERVICE_API_KEY: $CATALOG_SERVICE_API_KEY
              CATALOG_SERVICE_ENVIRONMENT_ID: $CATALOG_SERVICE_ENVIRONMENT_ID
              CATALOG_SERVICE_STORE_CODE: $CATALOG_SERVICE_STORE_CODE
              CATALOG_SERVICE_STORE_VIEW_CODE: $CATALOG_SERVICE_STORE_VIEW_CODE
              CATALOG_SERVICE_WEBSITE_CODE: $CATALOG_SERVICE_WEBSITE_CODE
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
              MESH_API_KEY:
                type: string
                description: API key for API Mesh authentication
              CATALOG_SERVICE_API_KEY:
                type: string
                description: API key for Catalog Service authentication
              CATALOG_SERVICE_ENVIRONMENT_ID:
                type: string
                description: Environment ID for Catalog Service
            annotations:
              require-adobe-auth: false
              final: true
