application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      kukla-integration-service:
        license: Apache-2.0
        actions:
          get-products:
            function: actions/get-products/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: info
              NODE_ENV: staging
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
              BYPASS_CACHE: false
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
            annotations:
              require-adobe-auth: false
              final: true
          download-file:
            function: actions/download-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
            annotations:
              require-adobe-auth: false
              final: true
          browse-files:
            function: actions/browse-files/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
            annotations:
              require-adobe-auth: false
              final: true
          delete-file:
            function: actions/delete-file/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
            annotations:
              require-adobe-auth: false
              final: true
          auth-token:
            function: actions/auth-token/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
            annotations:
              require-adobe-auth: false
              final: true
          get-products-mesh:
            function: actions/get-products-mesh/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              NODE_ENV: staging
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              S3_BUCKET: $S3_BUCKET
              AWS_REGION: $AWS_REGION
              MESH_API_KEY: $MESH_API_KEY
              API_MESH_ENDPOINT: $API_MESH_ENDPOINT
              RUNTIME_URL: $RUNTIME_URL
              AIO_runtime_namespace: $AIO_runtime_namespace
            parameters:
              COMMERCE_ADMIN_USERNAME:
                type: string
                description: Admin username for authentication
              COMMERCE_ADMIN_PASSWORD:
                type: string
                description: Admin password for authentication
              MESH_API_KEY:
                type: string
                description: API key for API Mesh authentication
            annotations:
              require-adobe-auth: false
              final: true
