application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      kukla-integration-service:
        license: Apache-2.0
        actions:
          get-products:
            function: actions/get-products/index.js
            web: "yes"
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              COMMERCE_URL: $COMMERCE_URL
              COMMERCE_ADMIN_USERNAME: $COMMERCE_ADMIN_USERNAME
              COMMERCE_ADMIN_PASSWORD: $COMMERCE_ADMIN_PASSWORD
            annotations:
              require-adobe-auth: false
              final: true
          download-file:
            function: actions/download-file/index.js
            web: "yes"
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
